### ISSUE TITLE
$list->getOPML() should be html escaped

### ISSUE THREAD

**Issue by eevleevs** [johansatge/workflowy-php#4]
Otherwise it will not be possible to restore if formatting tags are used.
Right now I am doing this to backup properly:

>         file_put_contents($dir . $date . '.opml.gz', gzencode(
>           preg_replace_callback('/(text|_note)="(.*?)"/', function ($matches) {
>             return $matches[1] . '="' . htmlspecialchars($matches[2]) . '"';
>           }, $list->getOPML())
>         ));

**Comment by johansatge** [comment]
Hi,

thanks for your feedback!

I'll try to fix that soon. (Of course, feel free to open a PR if you've got some free time!)

**Comment by johansatge** [comment]
Fixed in [ec927f4](https://github.com/johansatge/workflowy-php/commit/ec927f4cd3389a06a7008bd65619c981f1065ce5).

Let me know if you still have issues.
