### ISSUE TITLE
Timestamps broken

### ISSUE THREAD

**Issue by eevleevs** [johansatge/workflowy-php#7]
Hi, I am getting weird timestamps from $list->getLastModifiedTime() (new items in 2356), and nothing from $list->getCompletedTime(). Please check.

**Comment by johansatge** [comment]
Hi! thanks for reporting this.

It looks like WorkFlowy has updated the timestamps format in its internal API. I have updated mine to take that into account. The functions should be fixed if you update to `0.2.1`.

Let me know if you still reproduce the issue! thx.

**Comment by eevleevs** [comment]
Working here, thanks!
