### ISSUE TITLE
string(49) "Could not open the session with those credentials"

### ISSUE THREAD

**Issue by eevleevs** [johansatge/workflowy-php#8]
Hi, since yesterday I am getting the error above. Please check.

**Comment by johansatge** [comment]
Hi,

thanks for reporting this! Indeed it looks like the authentication UI has been updated recently, I have fixed the project accordingly. Things should work if you pull `0.2.2`.

Let me know if you still have issues.

**Comment by eevleevs** [comment]
Works, thanks!

**Comment by eevleevs** [comment]
Hi Johan, it happens again.

**Comment by johansatge** [comment]
Hey! Thank your for the report. It should have been fixed in #10.
