### ISSUE TITLE
Could not open the session with those credentials

### ISSUE THREAD

**Issue by jrmgx** [johansatge/workflowy-php#9]
Hello,

first of all thank you for this unofficial library, it is a pleasure to use and very handy.
That being said ; and with a fully understanding on the *unofficial* state ;
it seems that from today it does not work anymore.

Given valid credentials I receive this exception
```
WorkFlowyPHP\WorkFlowyException: Could not open the session with those credentials
```

I guess that Workflowy may have changed something?  
I don't have enough expertise in the reverse engineering of this API to test it further, maybe you can have a look and confirm.

Thank you

**Comment by jrmgx** [comment]
from what I see, `sid` is not present (at least as a field) in the response anymore

**Comment by jrmgx** [comment]
I've tried a fix see #10

**Comment by johansatge** [comment]
👍 I have published version `0.2.3` with your fix. Thanks again for the help!

**Comment by jrmgx** [comment]
Thanks to you for that reactivity

**Comment by jrmgx** [comment]
It does not seem that packagist.org has cough the update? can you do
something about it?

**Comment by johansatge** [comment]
Indeed, it seems Packagist didn't sync the package for some reason. It should be good now. ([package](https://packagist.org/packages/johansatge/workflowy-php))
